apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-app-rolebinding
  namespace: vault
subjects:
- kind: ServiceAccount
  name: sample-app-service-account
  namespace: vault
roleRef:
  kind: Role
  name: sample-app-role
  apiGroup: rbac.authorization.k8s.io